spring:
  application:
    name: flashsale-service
  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: flashsale-event:com.example.flashsaleservice.event.FlashSaleOrderEvent
      acks: all
      retries: 3

server:
  port: 8086